from django.contrib import admin
from django.contrib.auth.admin import UserAdmin as BaseUserAdmin
from django.contrib.auth.models import User
from django.forms.models import BaseInlineFormSet
from .models import (
    Category, Brand, Product, ProductImage, ProductSpecification, 
    Customer, Address, Order, OrderItem, Review
)

# --- Inlines (Manage these inside the Product Page) ---

class ProductSpecificationInline(admin.TabularInline):
    model = ProductSpecification
    extra = 1 # Shows 1 empty row by default

class ProductImageInline(admin.TabularInline):
    model = ProductImage
    extra = 1

# --- Main Admin Classes ---

@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    # What columns to show in the list view
    list_display = (
        'name', 
        'product_id', 
        'sku', 
        'brand', 
        'category', 
        'price', 
        'stock_quantity', 
        'is_active', 
        'is_featured'
    )
    
    # Sidebar filters
    list_filter = ('brand', 'category', 'is_active', 'is_featured', 'created_at')
    
    # Search box (Search by Name, SKU, or SS-ID)
    search_fields = ('name', 'description', 'sku', 'product_id')
    
    # Add the images and specs to the bottom of the product page
    inlines = [ProductSpecificationInline, ProductImageInline]
    
    # These fields are auto-generated by your model, so we make them Read-Only
    readonly_fields = ('product_id', 'slug', 'created_at', 'updated_at')
    
    # Organizing the layout (Optional, but looks nice)
    fieldsets = (
        ('Identification', {
            'fields': ('name', 'slug', 'product_id', 'sku')
        }),
        ('Relationships', {
            'fields': ('brand', 'category')
        }),
        ('Pricing', {
            'fields': ('price', 'wholesale_price', 'discount_price')
        }),
        ('Inventory & Status', {
            'fields': ('stock_quantity', 'is_active', 'is_featured')
        }),
        ('Media & Content', {
            'fields': ('image', 'short_description', 'description')
        }),
        ('Social Proof', {
            'fields': ('rating', 'reviews_count')
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )

@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ('name', 'slug')
    search_fields = ('name',)
    readonly_fields = ('slug',) # Auto-generated

@admin.register(Brand)
class BrandAdmin(admin.ModelAdmin):
    list_display = ('name', 'slug')
    search_fields = ('name',)
    readonly_fields = ('slug',) # Auto-generated


# This puts the "Wholesale/Retail" dropdown INSIDE the User page
class ProfileInline(admin.StackedInline):
    model = Customer
    can_delete = False
    verbose_name_plural = 'Customer Profile'
    fk_name = 'user'

# Unregister the default User Admin and register our own
# --- 1. CUSTOMER ADMIN ---
@admin.register(Customer)
class CustomerAdmin(admin.ModelAdmin):
    # Now you can see Email and Phone directly in the list
    list_display = ('name', 'email', 'phone_number', 'customer_type', 'user')
    list_filter = ('customer_type', 'created_at')
    search_fields = ('name', 'email', 'phone_number', 'user__username')
    
    # You can also edit the user link if needed, but usually read-only
    raw_id_fields = ('user',)


# --- 2. ADDRESS ADMIN ---
@admin.register(Address)
class AddressAdmin(admin.ModelAdmin):
    # Columns to show in the list
    list_display = ('customer', 'full_name', 'phone', 'address_type', 'division', 'district', 'sub_district', 'is_default')
    
    # Filters on the right side
    list_filter = ('division', 'address_type', 'is_default')
    
    # Search bar
    search_fields = ('full_name', 'phone', 'address', 'customer__name')



# --- 3. ORDER ADMIN ---
class OrderItemInlineFormSet(BaseInlineFormSet):
    def clean(self):
        super().clean()
        for form in self.forms:
            if not form.cleaned_data.get('price') and form.cleaned_data.get('product'):
                form.cleaned_data['price'] = form.cleaned_data['product'].price

class OrderItemInline(admin.TabularInline):
    model = OrderItem
    formset = OrderItemInlineFormSet
    extra = 1


@admin.register(Order)
class OrderAdmin(admin.ModelAdmin):
    readonly_fields = ('total_amount',)
    list_display = ('id', 'customer', 'total_amount', 'order_status', 'created_at')
    list_filter = ('order_status', 'created_at')
    search_fields = ('customer__name', 'customer__email', 'id')
    inlines = [OrderItemInline]


# --- 4. REVIEW ADMIN ---
@admin.register(Review)
class ReviewAdmin(admin.ModelAdmin):
    list_display = ('product', 'customer', 'rating', 'created_at')