# Generated by Django 5.2.8 on 2026-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unique_user_email_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Contact Email', max_length=254, unique=True),
        ),
    ]
