# Generated by Django 5.2.8 on 2026-02-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_division_lat_division_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='lat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='long',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
