# Generated by Django 5.2.8 on 2026-02-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_district_lat_district_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.division'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.subdistrict'),
        ),
    ]
