# Generated by Django 5.2.8 on 2026-02-01 14:16

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_district_alter_address_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='division', chained_model_field='division', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.district'),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_district',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='district', chained_model_field='district', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.subdistrict'),
        ),
    ]
