# Generated by Django 5.2.8 on 2026-02-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='social_avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
