from django.contrib import admin
# from django.forms.models import BaseInlineFormSet
from .models import (
    Category, Brand, Product, ProductImage, ProductSpecification,
    ProductVariant
)

# --- Inlines (Manage these inside the Product Page) ---


class ProductSpecificationInline(admin.TabularInline):
    model = ProductSpecification
    extra = 1  # Shows 1 empty row by default


class ProductImageInline(admin.TabularInline):
    model = ProductImage
    extra = 1


class ProductVariantInline(admin.TabularInline):
    model = ProductVariant
    extra = 1


# --- Main Admin Classes ---


@admin.register(Product)
class ProductAdmin(admin.ModelAdmin):
    # What columns to show in the list view
    list_display = (
        'name',
        'product_id',
        'sku',
        'brand',
        'category',
        'price',
        'stock_quantity',
        'is_active',
        'is_featured',
        'is_bestseller'
    )

    # Sidebar filters
    list_filter = ('brand', 'category', 'is_active',
                   'is_featured', 'is_bestseller', 'created_at')

    # Search box (Search by Name, SKU, or SS-ID)
    search_fields = ('name', 'description', 'sku', 'product_id')

    # Add the images and specs to the bottom of the product page
    inlines = [ProductSpecificationInline,
               ProductImageInline, ProductVariantInline]

    # These fields are auto-generated by your model, so we make them Read-Only
    readonly_fields = ('product_id', 'slug', 'created_at', 'updated_at')

    # Organizing the layout (Optional, but looks nice)
    fieldsets = (
        ('Identification', {
            'fields': ('name', 'slug', 'product_id', 'sku')
        }),
        ('Relationships', {
            'fields': ('brand', 'category', 'related_products')
        }),
        ('Pricing', {
            'fields': ('price', 'wholesale_price', 'discount_price')
        }),
        ('Inventory & Status', {
            'fields': ('stock_quantity', 'is_active', 'is_featured', 'is_bestseller')
        }),
        ('Media & Content', {
            'fields': ('image', 'short_description', 'description')
        }),
        ('Social Proof', {
            'fields': ('rating', 'reviews_count')
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at')
        }),
    )

    filter_horizontal = ('related_products',)


@admin.register(Category)
class CategoryAdmin(admin.ModelAdmin):
    list_display = ('name', 'slug', 'parent')
    search_fields = ('name',)
    readonly_fields = ('slug',)  # Auto-generated


@admin.register(Brand)
class BrandAdmin(admin.ModelAdmin):
    list_display = ('name', 'slug')
    search_fields = ('name',)
    readonly_fields = ('slug',)  # Auto-generated


# --- 4. REVIEW ADMIN ---
# Moved to reviews app
