# Generated by Django 5.2.8 on 2026-01-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_variant_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='paid_from',
            field=models.TextField(blank=True, help_text='Source or payer info', null=True),
        ),
    ]
