# Generated by Django 5.2.8 on 2026-01-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_paymentinfo_paid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='paid_from',
            field=models.CharField(blank=True, help_text='Source or payer info', null=True),
        ),
    ]
