# Generated by Django 5.2.8 on 2026-01-12 23:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_paymentinfo_paid_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
