# Generated by Django 5.2.8 on 2026-02-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentinfo_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_type',
            field=models.CharField(blank=True, help_text='Home, Office, etc.', max_length=20, null=True),
        ),
    ]
