# Generated by Django 5.2.8 on 2026-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_update_product_sku_simple_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='questions_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
